# syntax=docker/dockerfile:1

FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat

FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_PICADO_ID
ARG NEXT_PUBLIC_LA_ESQUINA_ID
ARG NEXT_PUBLIC_PICADO_FINO_PHONE
ARG NEXT_PUBLIC_LA_ESQUINA_PHONE
ARG NEXT_PUBLIC_PLACES_KEY
ARG NEXT_PUBLIC_PLACES_PICADO_ID
ARG NEXT_PUBLIC_PLACES_ESQUINA_ID

ENV NEXT_PUBLIC_API=$NEXT_PUBLIC_API
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_PICADO_ID=$NEXT_PUBLIC_PICADO_ID
ENV NEXT_PUBLIC_LA_ESQUINA_ID=$NEXT_PUBLIC_LA_ESQUINA_ID
ENV NEXT_PUBLIC_PICADO_FINO_PHONE=$NEXT_PUBLIC_PICADO_FINO_PHONE
ENV NEXT_PUBLIC_LA_ESQUINA_PHONE=$NEXT_PUBLIC_LA_ESQUINA_PHONE
ENV NEXT_PUBLIC_PLACES_KEY=$NEXT_PUBLIC_PLACES_KEY
ENV NEXT_PUBLIC_PLACES_PICADO_ID=$NEXT_PUBLIC_PLACES_PICADO_ID
ENV NEXT_PUBLIC_PLACES_ESQUINA_ID=$NEXT_PUBLIC_PLACES_ESQUINA_ID

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
